export const GAME_CONFIG = {
  width: 1280,
  height: 720,
  fixedStepSeconds: 1 / 120,
  maxFrameSeconds: 0.1,
  playfield: { left: 40, right: 1240, top: 32, bottom: 720, wallThickness: 8 },
  paddle: {
    width: 150,
    height: 20,
    y: 650,
    speed: 720,
    speedBoostMultiplier: 2.5,
  },
  input: {
    mouseSensitivity: 1,
  },
  ball: {
    radius: 9,
    speed: 240,
    speedAssistPercentageStep: 0.05,
    speedAssistMaximumPercentage: 0.25,
    multiballSpeedTransitionDurationSeconds: 1,
    spawnGap: 28,
    initialHorizontalRatio: 0.34,
    minHorizontalRatio: 0.14,
    maxHorizontalRatio: 0.82,
    trailSampleIntervalSeconds: 1 / 30,
  },
  levelUpTransition: {
    slowdownDurationSeconds: 1,
    speedupDurationSeconds: 1,
    overlayFadeOutDurationSeconds: 0.25,
    maxVisibleTrajectoryGhosts: 5,
  },
  bricks: {
    columns: 20,
    densityStartLevel: 1,
    densityFullLevel: 30,
    densityStartMinOccupancy: 4,
    densityStartMaxOccupancy: 7,
    densityFullMinOccupancy: 20,
    densityFullMaxOccupancy: 20,
    initialRowCount: 4,
    brickWidth: 56,
    brickHeight: 20,
    horizontalGap: 4,
    verticalEdgeGap: 4,
    fieldTopY: 32,
    dangerLineY: 520,
    speedClassDistribution: [
      { speedClass: 'SLOW', weight: 60 },
      { speedClass: 'MEDIUM', weight: 25 },
      { speedClass: 'FAST', weight: 10 },
      { speedClass: 'RUSH', weight: 5 },
    ],
    generationSeed: 0x5eed1234,
  },
  difficulty: {
    baseAverageBrickSpeed: 3.6,
    averageSpeedGrowthPerLevel: 1,
    baseSpeedRange: 3,
    speedRangeGrowthPerLevel: 0.5,
    speedClassRangePositions: { SLOW: 0, MEDIUM: 1 / 3, FAST: 2 / 3, RUSH: 1 },
    brickPressureAssistGraceSeconds: 7,
    brickPressureAssistMaximumLevels: 5,
    brickPressureAssistLevelsPerSecond: 1,
  },
  progression: {
    startingLevel: 1,
    initialXpRequirement: 10,
    initialRequirementIncrease: 15,
    xpIncreasePlateauLevel: 25,
    xpIncreaseDecayExponent: 0.88,
    plateauXpRequirement: 200,
    normalBrickXp: 1,
  },
  survival: {
    easyStartDurationSeconds: 30,
    rampEndSeconds: 12 * 60,
    winTimeSeconds: 17 * 60,
    rampStartDifficultyLevel: 1,
    rampEndDifficultyLevel: 16,
    enrageDensityMin: 20,
    enrageDensityMax: 20,
  },
  powers: {
    maxLevel: 5,
    maxOwned: 5,
    offerCount: 3,
    startingRerolls: 1,
    startingBans: 1,
    offerSeed: 0xc01dcafe,
    gunShotIntervalSeconds: 0.1,
    gunReloadSeconds: 4,
    gunMountInset: 16,
    projectileSpeed: 720,
    projectileLength: 10,
    electricRadiusInBrickPitches: 5,
    electricSameColumnThresholdTiles: 0.5,
    electricSameColumnUpwardPenaltyTiles: 1.5,
    electricLowerTargetTieToleranceTiles: 1,
    electricPrimaryTargetsByLevel: [2, 3, 4, 5, 5],
    fireHorizontalRadiusSpacesByLevel: [1, 2, 3, 4, 4],
    windRangeSpacesByLevel: [4, 5, 6, 7],
    splittingCooldownSecondsByLevel: [30, 25, 20, 15, 10],
    paddleOuterEdgeElevationDegreesByLevel: [40, 35, 30, 25, 15],
    fireEffectSeconds: 0.18,
    windEffectSeconds: 0.18,
    missileLaunchOffsets: [0, 0.2, -0.2, 0.4, -0.4],
    missileLaunchIntervalSeconds: 0.4,
    missileLevelFiveLaunchIntervalSeconds: 0.2,
    missileReloadSeconds: 6,
    missileDeploymentDurationSeconds: 0.35,
    missileDeploymentSpeed: 100,
    missileHomingInitialSpeed: 180,
    missileHomingMaximumSpeed: 720,
    missileHomingAcceleration: 600,
    missileTurnRateRadiansPerSecond: Math.PI * 2,
    missileCollisionRadius: 4,
    missileVerticalTieTolerance: 0.5,
  },
  run: {
    startingLives: 3,
  },
  debug: { enabled: true },
  rendering: {
    renderScale: 1,
    dangerGlowMaximumExpansion: 6,
    dangerGlowMaximumAlpha: 0.24,
    dangerAberrationMaximumOffset: 3,
    dangerAberrationMaximumAlpha: 0.22,
    dangerAberrationVibrationAmplitude: 0.75,
    dangerAberrationVibrationHz: 5,
    dangerVignetteMinimumIntensity: 0.18,
    dangerVignetteMaximumAlpha: 0.26,
    dangerVignetteSmoothingSeconds: 0.25,
    brickSpeedClassColors: {
      SLOW: 0x789b83,
      MEDIUM: 0x7891ad,
      FAST: 0xa5a9b0,
      RUSH: 0xad8293,
    },
  },
} as const;
