export const GAME_CONFIG = {
  width: 1280,
  height: 720,
  fixedStepSeconds: 1 / 120,
  maxFrameSeconds: 0.1,
  playfield: { left: 40, right: 1240, top: 32, bottom: 720, wallThickness: 8 },
  paddle: {
    width: 150,
    height: 20,
    y: 650,
    speed: 720,
    speedBoostMultiplier: 2.5,
  },
  input: {
    mouseSensitivity: 1,
  },
  ball: {
    radius: 9,
    speed: 360,
    spawnGap: 28,
    initialHorizontalRatio: 0.34,
    minHorizontalRatio: 0.14,
    maxHorizontalRatio: 0.82,
    trailSampleCount: 18,
    trailSampleIntervalSeconds: 1 / 30,
  },
  bricks: {
    columns: 15,
    initialRowCount: 4,
    brickWidth: 68,
    brickHeight: 20,
    horizontalGap: 8,
    verticalGap: 7,
    originX: 74,
    fieldTopY: 32,
    descentSpeed: 3,
    minimumBricksPerRow: 6,
    maximumBricksPerRow: 9,
    generationSeed: 0x5eed1234,
  },
  run: {
    startingLives: 3,
    lifeLostDelaySeconds: 1,
  },
  debug: { enabled: true },
  rendering: {
    renderScale: 1,
  },
} as const;
